### ISSUE TITLE
Stream Ollama response and speech

### ISSUE THREAD

**Issue by cabouezzi** [cabouezzi/PhotoManagement#26]
**User Story**
As a user, I don't want to sit and wait while the LLM generates a response.

**Description**
This enhancement will initiate audio as the LLM is generating a stream of tokens.

**Tasks**

- [x] Stream the LLM response
- [x] Use text-to-audio as the stream goes on
- [ ] Give an async option to invoke the LLM

**Dependencies**
#19
