### ISSUE TITLE
Create Basic Database System

### ISSUE THREAD

**Issue by cabouezzi** [cabouezzi/PhotoManagement#4]
**User Story**
As a customer, I want to be able to store my photos so that I can view them later.

**Description**
Provide a storage solution that can store all relevant data to each photo. The storage solution should be able to store and access images, metadata, and a description of the image. 

**Acceptance Criteria**

- [x] Store/retrieve an image and related metadata
- [x] Store/retrieve a description of an image
- [x] Connect the storage solution to the application

**Tasks**

- [x] Be able to store/retrieve an image
- [x] Be able to store/retrieve an images' metadata
- [x] Be able to store/retrieve an images' description
- [x] Connect the storage application

**Additional Notes**
The image is in binary format and the text is in text format (technically still binary). The best approach for binary data is through a filesystem solution. This can be done by having our images stored in the filesystem(e.g. image1.png) and having a corresponding file (e.g. image1.meta or image1.description). 
Another approach is to use a NoSQL database (e.g. MongoDB) to store everything together. Databases have performance and scalability issues  when (Transactional databases are not that great for static data[images]). Another solution would be to have a pointer to our images' location. This pointer would need to be updated when the image is moved.
