### ISSUE TITLE
Searching for Photos by Text

### ISSUE THREAD

**Issue by cabouezzi** [cabouezzi/PhotoManagement#6]
**User Story**
As a parent, I would like to find photos I have added using text description so that I can find pictures containing my family for a family album.

**Description**
Provide a search command that returns all photos from local file/storage system that match the text description provided.

**Acceptance Criteria**

- [x]  Takes a text description
- [x] search for photos using the text description generated by LLM
- [ ] users will be able to download the photos 

**Tasks**

- [x] create a command that takes in a text description argument
- [x] tokenize query and image descriptions
- [x] search stored images with query
- [x] create and return an array of JSON object containing the matching images

**Dependencies**
#4
